# Server port
server.port=8080

# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway routes
spring.cloud.gateway.routes[0].id=user-service-auth
spring.cloud.gateway.routes[0].uri=lb://USER-CAR-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

